apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webchat
  name: webchat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webchat
  template:
    metadata:
      labels:
        app: webchat
    spec:
      containers:
      - image: nginx:latest
        name: nginx
